# ----------

# This is the English language configuration file
# for transforming documents to HTML

# 2021-05-14

# The configuration file stores information about the paths used by scripts
# in the system.

# NOTE: All paths should be relative to the repo root, i.e. the folder containing
# the .git folder.

# ----------
# Documents

documents:
  path: "en/documents" # Name of the root folder where the documents are located.
  assets: "assets"     # path to the assets - child of documents
  lst: "sites.lst"       # The file used to define what files will be part of the final document
  tocs:
    - "sites.lst"
    # - "mining/mining.lst"
    # - "models/models.lst"
    # - "geometry/geometry.lst"
  # toc_summary:
  #   - 'release_notes.lst'

# ----------
# Templates

templates:
  path: "en/templates"
  pandoc_config: "html.yaml"
  # html_template: "tbw.template.html"
  # include_in_header:
  #   - "includes.partial.html"
  # include_before_body:
  #   - "header.partial.html"
  # include_after_body:
  #   - footer.partial.html

# ----------
# CSS

css:
  path: "en/css"
  css_files:
    - "tbw.css"
    - "tbw.syntax-highlight.css"

# ----------
# Output

output: "output/en/html_single"

# ----------
# Misc

# default timezone name to use for time calculations
default.tz: "America/Toronto"
