# ----------

# This is the English language configuration file
# for transforming documents to HTML

# 2021-05-14

# The configuration file stores information about the paths used by scripts
# in the system.

# NOTE: All paths should be relative to the repo root, i.e. the folder containing
# the .git folder.

# NOTE: You can use the `null` option for some of these variables.

# ----------
# Documents

documents:
  path: "en/documents"   # Name of the root folder where the documents are located. This is relative to the root of the repository.
  assets: "assets"       # path to the assets (images, videos, etc.). It is a child of the documents folder.
  lst: "sites.lst"       # The file used to define what Markdown content will be part of the final document
  tocs:
    - "sites.lst"                # The LST files that will be used to create table of contents. Add an entry for each item and an `index.md` will be created automatically in the same location in the folder structure as the LST file.
    # - "mining/mining.lst"
    # - "models/models.lst"
    # - "geometry/geometry.lst"
  # toc_summary:
  #   - 'release_notes.lst'

# ----------
# Templates

templates:
  path: "en/templates"                 # The name and path to the template folder. This is relative to the root of the repository.
  pandoc_config: "html.pandoc.yaml"    # The name of the Pandoc configuration file.
  # html_template: "tbw.template.html"
  # include_in_header:
  #   - "includes.partial.html"
  # include_before_body:
  #   - "header.partial.html"
  # include_after_body:
  #   - footer.partial.html

# ----------
# Misc

# default timezone name to use for time calculations
default.tz: "America/Toronto"
