# ----------

# These are common configuration items shared between different build processes.
# It should contain information specific to the repository and not too much on the
# output files.

# 2021-05-14

# The configuration file stores information about the paths used by scripts
# in the system.

# NOTE: All paths should be relative to the repo root, i.e. the folder containing
# the .git folder.

# NOTE: You can use the `null` option for some of these variables.

# ----------
# Documents

documents:
  path: "en/documents"   # Name of the root folder where the documents are located. This is relative to the root of the repository.
  assets: "assets"       # path to the assets (images, videos, etc.). It is a child of the documents folder.
  lst: "sites.lst"       # The file used to define what Markdown content will be part of the final document
  tocs:                  # A list of dictionaries representing LST files that we want to create index files for
    - lst: sites.lst     # The name and path of the LST file to use in the TOC process
      index: index.md    # The name and path of the TOC file to produce - generally it will be in the same folder as the lst
      depth: 6           # The depth of ATX headers to include in the TOC. It is a number from 0 to 6.
    # - lst: f1/f2/m1.md
    #   index: f1/fd/index.md
    #   depth: 0
    # - lst: t1/test.md
    #   index: t1/toc.md
    #   depth: 6


# ----------
# Misc

# default timezone name to use for time calculations
default.tz: "America/Toronto"
