# ----------

# This is the English language configuration file
# for transforming documents to HTML

# 2021-05-14

# The configuration file stores information about the paths used by scripts
# in the system.

# NOTE: All paths should be relative to the repo root, i.e. the folder containing
# the .git folder.

# ----------
# CSS

css:
  path: "en/css"
  css_files:
    - "tbw.css"
    - "tbw.syntax-highlight.css"

# ----------
# Output

output: "output/en/html"
