# ----------

# This is the English language configuration file
# for transforming documents to HTML

# 2021-05-14

# The configuration file stores information about the paths used by scripts
# in the system.

# NOTE: All paths should be relative to the repo root, i.e. the folder containing
# the .git folder.

# ----------
# Templates

templates:
  path: "en/templates"               # The name and path to the template folder. This is relative to the root of the repository.
  pandoc_config:                     # The names of the files to use to configure Pandoc. NOTE: The order matters, variables will be replaced by files further on down in the list
    - "common.pandoc.yaml"
    - "html.pandoc.yaml"
  # html_template: "tbw.template.html"
  # include_in_header:
  #   - "includes.partial.html"
  # include_before_body:
  #   - "header.partial.html"
  # include_after_body:
  #   - footer.partial.html


# ----------
# CSS

css:
  path: "en/css"
  css_files:
    - "tbw.css"
    - "tbw.syntax-highlight.css"

# ----------
# Output

output: "output/en/html"
