# ----------

# This is the English language configuration file
# for transforming documents to HTML, a single HTML file.

# Essentially, it is the exact same as the HTML except for the output folder.

# 2021-05-14

# The configuration file stores information about the paths used by scripts
# in the system.

# NOTE: All paths should be relative to the repo root, i.e. the folder containing
# the .git folder.

# ----------
# Output

output: "output/en/html_single"