# flake 8 configuration file
# https://cthoyt.com/2020/04/25/how-to-code-with-me-flake8.html
# https://flake8.pycqa.org/en/latest/user/configuration.html

# Unfortunately, this is an old system. It looks like pyproject.toml will be the cfg in the future: https://www.python.org/dev/peps/pep-0518/

[flake8]
enable-extensions = G
ignore =
    # A003 ; 'id' is a python builtin, consider renaming the class attribute
    # W503 ; line break before binary operator
    # S101 ; use of assert detected (useless with pytest)
    E501 ; line too long

exclude =
    .tox,
    .git,
    .venv,
    __pycache__,
    docs/source/conf.py,
    build,
    dist,
    tests/fixtures/*,
    *.pyc,
    *.egg-info,
    .cache,
    .eggs,
    md_docs/archive,
    tools/archive,
    output,
    tests
# import-order-style = pycharm

max-complexity = 8
max-annotations-complexity = 3
max-expression-complexity = 7
max-line-length = 120
show-source = true

# To make sure flake8-import-order knows about the name of your project
# module name, you need to specify it in tox.ini with the
# application-import-names option.
application-import-names =
    md_docs
    tools

